### ISSUE TITLE
create build definition

### ISSUE THREAD

**Issue by intracer** [AttemptToCallNil/Deuterium#1]
Project should have build definition (maven or gradle)
Dependencies should be defined in build definition using artifacts from maven repository, not links to local files like it is available now in .classpath file for Eclipse

```
 <classpathentry kind="lib" path="N:/eclipse/luaj-3.0.1/lib/luaj-jse-3.0.1.jar">
		<attributes>
			<attribute name="javadoc_location" value="file:/N:/eclipse/luaj-3.0.1/docs/api/"/>
		</attributes>
	</classpathentry>
 <classpathentry kind="lib" path="N:/eclipse/JSON-Java/json-java-2015-10-29.jar"/>
```

**Comment by AttemptToCallNil** [comment]
Thanks for feedback. As soon as I have the time, I will start working. I am trying to get a working build just for myself at the moment (with varying success), and as soon as I finish the current bug-fixing exercise (for example, the JSON parser is a piece of [REDACTED]: it works, but barely), I will work on this issue.

**Comment by AttemptToCallNil** [comment]
Migration to Maven seems to be complete (it took quite a while, but I managed to get a good archive build). Please tell me if there are any problems now, or if the issue is resolved.
